### ISSUE TITLE
Error: odd number of arguments

### ISSUE THREAD

**Issue by Elijas** [yvangodard/icalsync#2]
After 1. creating a google api app, 2. editing config file to add google app credentials and 3. accepting access

`./icalsync --calendar-id <CALENDAR_ID>@import.calendar.google.com`

I receive error

```
/home/user/icalsync/config.rb:1: Use RbConfig instead of obsolete and deprecated Config.
/home/user/icalsync/lib/google/event.rb:465:in `[]': odd number of arguments for Hash (ArgumentError)
	from /home/user/icalsync/lib/google/event.rb:465:in `parse_recurrence_rule'
	from /home/user/icalsync/lib/google/event.rb:451:in `new_from_feed'
	from /home/user/icalsync/lib/google/event.rb:248:in `block in build_from_google_feed'
	from /home/user/icalsync/lib/google/event.rb:248:in `collect'
	from /home/user/icalsync/lib/google/event.rb:248:in `build_from_google_feed'
	from /home/user/icalsync/lib/google/calendar.rb:288:in `block in event_lookup_all'
	from /home/user/icalsync/lib/google/calendar.rb:275:in `loop'
	from /home/user/icalsync/lib/google/calendar.rb:275:in `event_lookup_all'
	from /home/user/icalsync/lib/google/calendar.rb:103:in `events_all'
	from /home/user/icalsync/icalsync.rb:244:in `sync'
	from main.rb:30:in `<main>'
```

**Comment by Elijas** [comment]
with a quickfix outlined in the pullrequest another error pops
```
./icalsync --calendar-id <CALENDAR_ID>@import.calendar.google.com --file ./caltmp.ics
```
Results in
```
./icalsync --calendar-id <CALENDAR_ID>@import.calendar.google.com --file ./caltmp.ics
/home/user/calsync/config.rb:1: Use RbConfig instead of obsolete and deprecated Config.
W, [2017-01-02T22:59:17.058206 #6250]  WARN -- : No method "sequence=" for component #<Icalendar::Timezone:0x00000001e6dab0>. Appending to custom.
Waiting for 1.212 sec and resend
Waiting for 2.889 sec and resend
Waiting for 4.156 sec and resend
Waiting for 8.361 sec and resend
Waiting for 16.864 sec and resend
...
```

**Comment by Elijas** [comment]
Any updates?
